name: "build"
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '14' ]
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-java@v3.11.0
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Run docker
        run: |
          cd COOL
          chmod +x *.sh
          ./init.sh
          ./build.sh
          ./download.sh
          ./start.sh
      - name: Build
        run: |
          cd COOL
          chmod +x ./gradlew
          ./gradlew --stacktrace --scan
      - name: Stop docker
        run: |
          cd COOL
          ./stop.sh
  release:
    needs:
      - build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - uses: actions/setup-java@v3.11.0
        with:
          distribution: 'adopt'
          java-version: '14'
      - name: Deploy
        run: |
          cd COOL
          chmod +x ./gradlew
          ./gradlew shadowJar
      - name: Release
        run: |
          npm install
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
